// Read https://raw.githubusercontent.com/reginaldford/sms/main/LICENSE.txt for license information

sm_object *sm_add();
sm_object *sm_add_uint8_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_add_uint8_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_uint8_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_uint8_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_int64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_add_f64_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_add_f64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_f64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_add_f64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_minus();
sm_object *sm_minus_uint8_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_uint8_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_uint8_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_uint8_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_int64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_uint8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_int64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_f64(sm_object *o0, sm_object *o1);
