// Read https://raw.githubusercontent.com/reginaldford/sms/main/LICENSE.txt for license information

sm_object *sm_add();
sm_object *sm_add_ui8_and_ui8(sm_object *ui8_o0, sm_object *ui8_o1);
sm_object *sm_add_ui8_and_ui64(sm_object *ui8_o0, sm_object *ui64_o1);
sm_object *sm_add_ui8_and_i64(sm_object *ui8_o0, sm_object *i64_o1);
sm_object *sm_add_ui8_and_f64(sm_object *ui8_o0, sm_object *f64_o1);
sm_object *sm_add_ui64_and_ui8(sm_object *ui64_o0, sm_object *ui8_o1);
sm_object *sm_add_ui64_and_ui64(sm_object *ui64_o0, sm_object *ui64_o1);
sm_object *sm_add_ui64_and_i64(sm_object *ui64_o0, sm_object *i64_o1);
sm_object *sm_add_ui64_and_f64(sm_object *ui64_o0, sm_object *f64_o1);
sm_object *sm_add_i64_and_ui8(sm_object *i64_o0, sm_object *ui8_o1);
sm_object *sm_add_i64_and_ui64(sm_object *i64_o0, sm_object *ui64_o1);
sm_object *sm_add_i64_and_i64(sm_object *i64_o0, sm_object *i64_o1);
sm_object *sm_add_i64_and_f64(sm_object *i64_o0, sm_object *f64_o1);
sm_object *sm_add_f64_and_ui8(sm_object *f64_o0, sm_object *ui8_o1);
sm_object *sm_add_f64_and_ui64(sm_object *f64_o0, sm_object *ui64_o1);
sm_object *sm_add_f64_and_i64(sm_object *f64_o0, sm_object *i64_o1);
sm_object *sm_add_f64_and_f64(sm_object *f64_o0, sm_object *f64_o1);

sm_object *sm_minus();
sm_object *sm_minus_ui8_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_ui8_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_ui8_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_ui8_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_ui64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_ui64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_ui64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_ui64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_i64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_i64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_i64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_i64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_minus_f64_and_f64(sm_object *o0, sm_object *o1);

sm_object *sm_times();
sm_object *sm_times_ui8_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_times_ui8_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_times_ui8_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_times_ui8_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_times_ui64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_times_ui64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_times_ui64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_times_ui64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_times_i64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_times_i64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_times_i64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_times_i64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_times_f64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_times_f64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_times_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_times_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_times_f64_and_f64(sm_object *o0, sm_object *o1);

sm_object *sm_divide();
sm_object *sm_divide_ui8_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_divide_ui8_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_ui8_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_ui8_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_ui64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_divide_ui64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_ui64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_ui64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_i64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_divide_i64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_i64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_i64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_f64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_divide_f64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_divide_f64_and_f64(sm_object *o0, sm_object *o1);

sm_object *sm_gt();
sm_object *sm_gt_ui8_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_gt_ui8_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_ui8_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_ui8_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_ui64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_gt_ui64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_ui64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_ui64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_i64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_gt_i64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_i64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_i64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_f64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_gt_f64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_gt_f64_and_f64(sm_object *o0, sm_object *o1);

sm_object *sm_lt();
sm_object *sm_lt_ui8_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_lt_ui8_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_ui8_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_ui8_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_ui64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_lt_ui64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_ui64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_ui64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_i64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_lt_i64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_i64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_i64_and_f64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_f64_and_ui8(sm_object *o0, sm_object *o1);
sm_object *sm_lt_f64_and_ui64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_f64_and_i64(sm_object *o0, sm_object *o1);
sm_object *sm_lt_f64_and_f64(sm_object *o0, sm_object *o1);
