name: C/CPP template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make check
      run: sudo apt install -y bison flex gcc make && make check

